### ISSUE TITLE
Upgrade dependencies to support attrs 23

### ISSUE THREAD

**Issue by mattjudge** [FHPythonUtils/FHConfParser#1]
Hi! Would it be possible to update this project's dependencies to support attrs 23?

Thanks!

**Comment by FredHappyface** [comment]
Yeah no problems! I'll most likely update deps for all of my packages over the next few months!

**Comment by ringohoffman** [comment]
Is it possible to remove the upper bound on `attrs` and to publish a patch at least?

I am potentially going to have to stop using `licensecheck` due to version solving conflicts with 2 of my other dependencies, neither of which place an upper bound on `attrs`. With the bound, we are trading a potential incompatibility for a definite incompatibility.

* [hypothesis 6.92.2 depends on attrs>=22.2.0](https://github.com/HypothesisWorks/hypothesis/blob/6da7c6f9b7f8b838fcc83e3c4274cc4b1a56896b/hypothesis-python/setup.py#L99)
* [pytest-subtests 0.11.0 depends on attrs>=19.2.0](https://github.com/pytest-dev/pytest-subtests/blob/c1b90cbe4797bc15f83decc74033a6550fa23462/setup.cfg#L31)

**Comment by FredHappyface** [comment]
Hi thanks for the poke on this! I've released https://github.com/FHPythonUtils/FHConfParser/releases/tag/2024 which should fix this

**Comment by mattjudge** [comment]
Thanks for the update! Given that attrs follows calendar versioning, with "generous backwards-compatibility guarantees", is it worth removing the upper bound in the requirements? (Especially since, with calendar versioning, pinning the version like this doesn't imply any compatibility).

https://github.com/python-attrs/attrs/security#supported-versions

**Comment by FredHappyface** [comment]
That's a very good point tbh.

My personal opinion is that many implementations or semver rarely follow it by the letter which has made for some interesting professional conversations (turns out us software engineers can be quite opinionated). 

My use of Calver is typically that I will hold off the most breaking changes until a new year but I don't make any guarantees. Though I do try and avoid them particularly with some of my libs being used more broadly. Or at least add deprecation notices for 12+ months 

With my existing calver deps I tend to use current year and next year as a sort of "compromise" so that global libs are unlikely to hold back deps for others but to try and capture the idea of compatible versions. For example version 23 is more likely to be incompatible with version 26, than compared to say, 24. 

Though any thoughts or reading materials are absolutely welcome on the topic of versioning!

:)

**Comment by kthy** [comment]
I'm having the same issue now with licensecheck and attrs, and another package that requires attrs>=25 … that upper bound for a calver package is going to give you annual update requests, and in my experience Hynek (attrrs author) is extremely good about not breaking backwards compatibility.
